Repository higherkindness/mu-haskell, pull requests merged in 2020-09, with the labels that each got.

#221 Fix import of 'oneof' fields
  adapter/protobuf/src/Mu/Quasi/ProtoBuf.hs
  core/schema/src/Mu/Schema/Class.hs
Labels: bug, protobuf

#223 Conversion to logical types
  core/schema/mu-schema.cabal
  core/schema/src/Mu/Schema.hs
  core/schema/src/Mu/Schema/Class.hs
Labels: enhancement, schema

#222 Keep all annotations from .proto files
  adapter/protobuf/src/Mu/Adapter/ProtoBuf.hs
  adapter/protobuf/src/Mu/Quasi/ProtoBuf.hs
  adapter/protobuf/test/ProtoBuf.hs
  grpc/client/src/Mu/GRpc/Client/Examples.hs
  grpc/server/exe/ExampleServer.hs
Labels: protobuf

#224 Add video resources to readme! 📹
  README.md
Labels: docs, documentation, enhancement

#228 Fix and update stack.yaml and nix
  default.nix
  stack-14.yaml
  stack-nightly.yaml
  stack.yaml
Labels: bug, ci

#217 [WIP] Servant support
  .gitignore
  cabal.project
  core/rpc/mu-rpc.cabal
  core/rpc/src/Mu/Rpc/Annotations.hs
  core/rpc/src/Mu/Rpc/Examples.hs
  servant/server/CHANGELOG.md
  servant/server/LICENSE
  servant/server/Setup.hs
  servant/server/exe/ExampleServer.hs
  servant/server/hie.yaml
  servant/server/mu-servant-server.cabal
  servant/server/src/Mu/Servant/Server.hs
  stack-14.yaml
  stack-nightly.yaml
  stack.yaml
Labels: enhancement, help wanted, protobuf

#229 Port health check to use Servant + fix a few corner cases
  examples/health-check/mu-example-health-check.cabal
  examples/health-check/src/Definition.hs
  examples/health-check/src/Server.hs
  servant/server/exe/ExampleServer.hs
  servant/server/src/Mu/Servant/Server.hs
Labels: rpc
